HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTIONS="false"
COMPLETION_WAITING_DOTS="true"

HISTSIZE=50000
SAVEHIST=50000
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=true
HISTFILE=${HOME}/.zsh_history
HISTORY_IGNORE="(l[alsh]#( *)#)"

export BROWSER=open
